version: 2.0

workflows:
  build:
    name: Build and Test
    on:
      push:
        branches:
          - main
    jobs:
      - name: Build
        image: codemagic/react-native
        steps:
          - checkout
